#!/usr/bin/env bash

# Copyright 2022 by moshix
# AccessAudit installer

#echo "configure rsyslog"
logextension=`date "+%F-%T"`
logit () {
    # log to file all messages
    logdate=`date "+%F-%T"`
    echo "$logdate:$1" >> ./logs/configrsyslog.log.$logextension
}

set_colors() {
    red=`tput setaf 1`
    green=`tput setaf 2`
    yellow=`tput setaf 3`
    blue=`tput setaf 4`
    magenta=`tput setaf 5`
    cyan=`tput setaf 6`
    white=`tput setaf 7`
    blink=`tput blink`
    rev=`tput rev`
    reset=`tput sgr0`
}

#   *.* @your-server-hostname:3434

if [ -z $1 ]; then
    echo "You must provide immudb Vault API Key as first argument"
    exit 1
fi

echo "Using Vault Key $1"

mkdir -p /etc/accessaudit/
cat > /etc/accessaudit/env <<EOF
VAULT_API_KEY=$1
VAULT_URL=https://vault.immudb.io/ics/api/v1/ledger/default/collection/default/document
EOF

cat > /usr/bin/forward-logs-to-vault.sh <<EOF
#!/bin/bash
source /etc/accessaudit/env
while read line; do
  curl -X 'PUT' "\$VAULT_URL"  -H 'accept: application/json' -H "X-API-Key: \$VAULT_API_KEY"   -H 'Content-Type: application/json'   -d "\$line"
done
EOF

chmod +x /usr/bin/forward-logs-to-vault.sh


cat > /etc/rsyslog.d/99-immudb-vault.conf <<EOF
module(load="omprog")
    
template(name="json-template" type="list") {
    constant(value="{")
      constant(value="\"timestamp\":\"")     property(name="timereported" dateFormat="rfc3339")
      constant(value="\",\"message\":\"")    property(name="msg" format="json")
      constant(value="\",\"host\":\"")       property(name="hostname")
      constant(value="\",\"severity\":\"")   property(name="syslogseverity-text")
      constant(value="\",\"facility\":\"")   property(name="syslogfacility-text")
      constant(value="\",\"syslogtag\":\"")  property(name="syslogtag")
    constant(value="\"}\n")
}


authpriv.* action(type="omprog"
            binary="/usr/bin/forward-logs-to-vault.sh"
            template="json-template")
EOF
