#!/usr/bin/env bash                                                                                                                                  

# Copyright 2022 by moshix
# AccessAudit installer

echo "creating database AUDIT "
logextension=`date "+%F-%T"`
logit () {
    # log to file all messages
    logdate=`date "+%F-%T"`
    echo "$logdate:$1" >> ./logs/startimmudb.log.$logextension
}

set_colors() {
    red=`tput setaf 1`
    green=`tput setaf 2`
    yellow=`tput setaf 3`
    blue=`tput setaf 4`
    magenta=`tput setaf 5`
    cyan=`tput setaf 6`
    white=`tput setaf 7`
    blink=`tput blink`
    rev=`tput rev`
    reset=`tput sgr0`
}


# main
set_colors
# This script should be called from the main install script, which will
# define $SUDO for us
if [[ -z "$SUDO" ]]; then
    echo "${rev}${red}😬 The createimmudb script should only be called by the AccessAudit install script.${reset}"
    exit 1
fi

