#!/usr/bin/env bash

# Copyright 2022 by moshix
# AccessAudit installer

#echo "getting immudb"

logextension=`date "+%F-%T"`
logit () {
    # log to file all messages
    logdate=`date "+%F-%T"`
    echo "$logdate:$1" >> ./logs/getimmudb.log.$logextension
}

set_colors() {
    red=`tput setaf 1`
    green=`tput setaf 2`
    yellow=`tput setaf 3`
    blue=`tput setaf 4`
    magenta=`tput setaf 5`
    cyan=`tput setaf 6`
    white=`tput setaf 7`
    blink=`tput blink`
    rev=`tput rev`
    reset=`tput sgr0`
}

exit_with_error () {
# exit but show error
msg=$1
echo "${red} Catastrophic error: $msg ${reset}"
exit 1
}


# main starts here
set_colors

# This script should be called from the main install script, which will
# define $SUDO for us
if [[ -z "$SUDO" ]]; then
    echo "${rev}${red}😬 The getimmudb script should only be called by the AccessAudit install script.${reset}"
    exit 1
fi

logit "getimmudb with sudo - OK $(date)"

#check if docker is present
if [ -x "$(command -v docker)" ]; then
    logit "Docker is installed - OK $(date)"
    # command
else
    echo "${red}😬 AccessAudit requires Docker to be installed on your system. Please install docker and restart the install script${reset}"
    # command
fi


echo "${green}Docker is present in your system -  OK${reset}"
logit "Docker is present - OK $(date)"

# check if immudb is already installed
if [ $( $SUDO docker ps -a | grep immudb | wc -l ) -gt 0 ]; then
  echo "${red}😬 immudb is already installed. Start the configure script instead!${reset}"
else
  echo "immudb not yet installed"
  immudbexist=0
  logit "immudb not yet present  - OK $(date)"
fi


# Allocate database directory locally for backups etc. 
$SUDO mkdir -p /opt/immudb/db/ || exit_with_error "Cannot allocate /opt/immudb/db for immmudb audit database. Exciting..."
logit "allocated /opt/immudb/db - OK $(date)"
echo "${green} Audit database directory allocated in /opt/immudb/db ${reset}"

# get immudb container now
$SUDO docker run --restart always --publish 3322:3322 -d  -v /opt/immudb/db:/var/lib/immudb --name immudb codenotary/immudb:latest || "${red}Catastrophic error. Exiting...${reset}"; exit 1
logit "ran docker run codenotary/immudb - OK $(date)"

# now let's check if immudb is running. 
if [ $( $SUDO docker ps -a | grep immudb | wc -l ) -gt 0 ]; then
  echo "${green}immudb is now  installed. Good!${reset}"
else
  echo "${red}😬 Oh no. Catastrophic error. We can't get immudb to run on Docker. Check the logs. ${reset}"
  exit 1
fi
