#!/usr/bin/env bash                                                                                                                                  

# Copyright 2022 by moshix
# AccessAudit installer

echo "getting immudb"
logextension=`date "+%F-%T"`
logit () {
    # log to file all messages
    logdate=`date "+%F-%T"`
    echo "$logdate:$1" >> ./logs/startimmudb.log.$logextension
}

set_colors() {
    red=`tput setaf 1`
    green=`tput setaf 2`
    yellow=`tput setaf 3`
    blue=`tput setaf 4`
    magenta=`tput setaf 5`
    cyan=`tput setaf 6`
    white=`tput setaf 7`
    blink=`tput blink`
    rev=`tput rev`
    reset=`tput sgr0`
}


# main
set_colors

# command 
[ ! "$(docker ps -a | grep <name>)" ] $SUDO docker run --restart always --publish 3322:3322 -d  -v /opt/immudb/db:/var/lib/immudb --name immudb codenotary/immudb:latest 
logit "start immudb - OK $(date)"

# now copy immuclient from container into AccessAudit directory
$SUDO docker cp codneotary/immudb:latest:/usr/local/bin/immuclient . 
