#!/usr/bin/env bash                                                                                                                                  

# Copyright 2022 by moshix
# AccessAudit installer

echo "starting immudb and copying relevant files down"
logextension=`date "+%F-%T"`
logit () {
    # log to file all messages
    logdate=`date "+%F-%T"`
    echo "$logdate:$1" >> ./logs/startimmudb.log.$logextension
}

set_colors() {
    red=`tput setaf 1`
    green=`tput setaf 2`
    yellow=`tput setaf 3`
    blue=`tput setaf 4`
    magenta=`tput setaf 5`
    cyan=`tput setaf 6`
    white=`tput setaf 7`
    blink=`tput blink`
    rev=`tput rev`
    reset=`tput sgr0`
}


# main
set_colors
# This script should be called from the main install script, which will
# define $SUDO for us
if [[ -z "$SUDO" ]]; then
    echo "${rev}${red}😬 The startimmudb script should only be called by the AccessAudit install script.${reset}"
    exit 1
fi

# make sure immudb is running
[ ! "$(docker ps -a | grep immudb)" ] $SUDO docker run --restart always --publish 3322:3322 -d  -v /opt/immudb/db:/var/lib/immudb --name immudb codenotary/immudb:latest 
logit "start immudb - OK $(date)"

# check if wget is intalled
if ! command -v wget &> /dev/null
then
    echo "${red}😬 wget command is not installed. Pls install wget and restart the install script. ${reset}"
    logit "wget not installed!!1 $(date)"
    exit 1
fi

# obtain immuclient
wget https://github.com/codenotary/immudb/releases/download/v1.4.1/immuclient-v1.4.1-linux-amd64-static || echo "${red}😬 Download of immuclient failed! Exiting...${reset}"; logit "immuclient download failed $(date)"; exit 1

if [ -f "immuclient-v1.4.1-linux-amd64-static" ] ; then
	logit "immuclient download complete - OK $(date)"
	echo "${green} Obtained immuclient !! Yeah ${reset}"
	mv immuclient-v1.4.1-linux-amd64-static immuclient
    else
        logit "immuclient download not complete!! $(date)"
         echo "${red}Download of immuclient did not complete! check resons and restart install. Exiting...${reset}"	
	 exit 1
fi

	mv immuclient-v1.4.1-linux-amd64-static immuclient

# now we have immudb running and immuclient installed

